---
- gather_facts: false
  hosts: localhost
  vars_files:
    - Server_Inventory_hosts.yml
  tasks:
  - name: Create a change ticket in SNOW 
    register: new_change_request
    snow_record:
      data:
        u_environment: "Production"
        cmdb_ci: "{{item.CI}}"
        start_date: "{{item.Release_date}}"
        short_description: "{{item.Short_Description}}"
        category: "Applications Software"
        assignment_group: "Change Management"
        assigned_to: "Change Manager"
        u_change_coordinator: "{{item.Change_Coordinator}}"
        u_approver: "{{item.Technical_Approver}}"
        type: "Normal"
        implementation_plan: "{{item.Implemention_Plan}}"
        backout_plan: "{{item.BackoutPlan}}"
        test_plan: "{{item.ValidationPlan}}"
        requested_by: Abel Tuter
        description: "{{item.Description}}"
        u_director_approval: '.Caitlin Reiniger'
        u_product_approval: '.Abraham Lincoln'
        u_sr_director_approval: '.Adela Cervantsz'
        u_vp_approval: '.Barbara Hindley'
      instance: dev99640
      password: 9tdEV1gUluAW
      state: present
      table: change_request
      username: admin
    with_items:
        - "{{ serverinventory }}"
#    register: new_change_request
#- debug: var=new_change_request.record.number
